# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactInfoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 748)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_analysis = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_analysis.sizePolicy().hasHeightForWidth())
        self.btn_analysis.setSizePolicy(sizePolicy)
        self.btn_analysis.setStyleSheet("")
        self.btn_analysis.setFlat(False)
        self.btn_analysis.setObjectName("btn_analysis")
        self.horizontalLayout_3.addWidget(self.btn_analysis)
        self.btn_emotion = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_emotion.sizePolicy().hasHeightForWidth())
        self.btn_emotion.setSizePolicy(sizePolicy)
        self.btn_emotion.setFlat(False)
        self.btn_emotion.setObjectName("btn_emotion")
        self.horizontalLayout_3.addWidget(self.btn_emotion)
        self.btn_report = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_report.sizePolicy().hasHeightForWidth())
        self.btn_report.setSizePolicy(sizePolicy)
        self.btn_report.setFlat(False)
        self.btn_report.setObjectName("btn_report")
        self.horizontalLayout_3.addWidget(self.btn_report)
        self.btn_back = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setText("")
        self.btn_back.setFlat(False)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        self.toolButton_output = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_output.sizePolicy().hasHeightForWidth())
        self.toolButton_output.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../data/icons/output.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_output.setIcon(icon)
        self.toolButton_output.setCheckable(False)
        self.toolButton_output.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_output.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_output.setAutoRaise(True)
        self.toolButton_output.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_output.setObjectName("toolButton_output")
        self.horizontalLayout_3.addWidget(self.toolButton_output)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_analysis.setText(_translate("Form", "统计信息"))
        self.btn_emotion.setText(_translate("Form", "情感分析"))
        self.btn_report.setText(_translate("Form", "年度报告"))
        self.toolButton_output.setText(_translate("Form", "导出聊天记录"))
