# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinfoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1120, 720)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setAutoFillBackground(False)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1120, 720))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 60, 291, 82))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_avatar = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_avatar.setMinimumSize(QtCore.QSize(80, 80))
        self.label_avatar.setObjectName("label_avatar")
        self.horizontalLayout.addWidget(self.label_avatar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_wxid = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_wxid.setObjectName("label_wxid")
        self.verticalLayout.addWidget(self.label_wxid)
        self.label_city = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_city.setObjectName("label_city")
        self.verticalLayout.addWidget(self.label_city)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_avatar.setText(_translate("Dialog", "TextLabel"))
        self.label_name.setText(_translate("Dialog", "TextLabel"))
        self.label_wxid.setText(_translate("Dialog", "TextLabel"))
        self.label_city.setText(_translate("Dialog", "TextLabel"))
