# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extrabuf.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xtrabuf.proto\x12\x0c\x61pp.protobuf\"d\n\x08\x45xtraBuf\x12.\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x1d.app.protobuf.ExtraBuf.Struct\x1a(\n\x06Struct\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\tB\tZ\x07.;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extrabuf_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.;proto'
  _globals['_EXTRABUF']._serialized_start=32
  _globals['_EXTRABUF']._serialized_end=132
  _globals['_EXTRABUF_STRUCT']._serialized_start=92
  _globals['_EXTRABUF_STRUCT']._serialized_end=132
# @@protoc_insertion_point(module_scope)
