# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_groupUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 720)
        self.error = QtWidgets.QLabel(Frame)
        self.error.setGeometry(QtCore.QRect(550, 80, 101, 16))
        self.error.setAutoFillBackground(False)
        self.error.setStyleSheet("color:red")
        self.error.setText("")
        self.error.setObjectName("error")
        self.tips = QtWidgets.QLabel(Frame)
        self.tips.setGeometry(QtCore.QRect(290, 630, 121, 16))
        self.tips.setObjectName("tips")
        self.layoutWidget = QtWidgets.QWidget(Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 70, 401, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.group_name = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_name.setFont(font)
        self.group_name.setObjectName("group_name")
        self.horizontalLayout_2.addWidget(self.group_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.group_intro = QtWidgets.QTextEdit(self.layoutWidget)
        self.group_intro.setObjectName("group_intro")
        self.horizontalLayout.addWidget(self.group_intro)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_set_gAvatar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_set_gAvatar.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_set_gAvatar.setMaximumSize(QtCore.QSize(100, 50))
        self.btn_set_gAvatar.setObjectName("btn_set_gAvatar")
        self.horizontalLayout_3.addWidget(self.btn_set_gAvatar)
        self.avatar_img = QtWidgets.QLabel(self.layoutWidget)
        self.avatar_img.setMinimumSize(QtCore.QSize(100, 100))
        self.avatar_img.setMaximumSize(QtCore.QSize(100, 100))
        self.avatar_img.setText("")
        self.avatar_img.setObjectName("avatar_img")
        self.horizontalLayout_3.addWidget(self.avatar_img)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_create = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_create.setFont(font)
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout.addWidget(self.btn_create)
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(260, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("一纸情书")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.back = QtWidgets.QPushButton(Frame)
        self.back.setGeometry(QtCore.QRect(0, 0, 91, 28))
        self.back.setObjectName("back")
        self.toolButton = QtWidgets.QToolButton(Frame)
        self.toolButton.setGeometry(QtCore.QRect(750, 0, 47, 21))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.tips.setText(_translate("Frame", "创建群聊成功"))
        self.label_2.setText(_translate("Frame", "群  名:"))
        self.group_name.setText(_translate("Frame", "请输入群名"))
        self.label.setText(_translate("Frame", "群简介:"))
        self.group_intro.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在这里介绍你的群聊（不超过150字）</p></body></html>"))
        self.btn_set_gAvatar.setText(_translate("Frame", "选择群头像"))
        self.btn_create.setText(_translate("Frame", "创建"))
        self.label_3.setText(_translate("Frame", "创建群聊"))
        self.back.setText(_translate("Frame", "返回"))
        self.toolButton.setText(_translate("Frame", "..."))
