# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GroupUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1120, 720)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 70, 322, 651))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_create_group = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_create_group.setObjectName("btn_create_group")
        self.horizontalLayout.addWidget(self.btn_create_group)
        self.btn_add_group = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_add_group.setObjectName("btn_add_group")
        self.horizontalLayout.addWidget(self.btn_add_group)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 0, 800, 720))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_msg = QtWidgets.QFrame(self.frame)
        self.frame_msg.setGeometry(QtCore.QRect(0, 0, 800, 720))
        self.frame_msg.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_msg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_msg.setObjectName("frame_msg")
        self.message = QtWidgets.QTextBrowser(self.frame_msg)
        self.message.setGeometry(QtCore.QRect(0, 40, 800, 540))
        self.message.setObjectName("message")
        self.textEdit = QtWidgets.QTextEdit(self.frame_msg)
        self.textEdit.setGeometry(QtCore.QRect(0, 580, 800, 140))
        self.textEdit.setObjectName("textEdit")
        self.l_g_name = QtWidgets.QLabel(self.frame_msg)
        self.l_g_name.setGeometry(QtCore.QRect(10, 0, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l_g_name.setFont(font)
        self.l_g_name.setText("")
        self.l_g_name.setObjectName("l_g_name")
        self.btn_sendMsg = QtWidgets.QPushButton(self.frame_msg)
        self.btn_sendMsg.setGeometry(QtCore.QRect(678, 668, 121, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btn_sendMsg.setFont(font)
        self.btn_sendMsg.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_sendMsg.setMouseTracking(False)
        self.btn_sendMsg.setAutoFillBackground(False)
        self.btn_sendMsg.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    \n"
"    padding: 10px;\n"
"    color:rgb(5,180,104);\n"
"}")
        self.btn_sendMsg.setIconSize(QtCore.QSize(40, 40))
        self.btn_sendMsg.setCheckable(False)
        self.btn_sendMsg.setAutoDefault(True)
        self.btn_sendMsg.setObjectName("btn_sendMsg")
        self.toolButton = QtWidgets.QToolButton(self.frame_msg)
        self.toolButton.setGeometry(QtCore.QRect(750, 10, 47, 21))
        self.toolButton.setObjectName("toolButton")
        self.btn_del_group = QtWidgets.QPushButton(self.frame_msg)
        self.btn_del_group.setGeometry(QtCore.QRect(650, 10, 93, 28))
        self.btn_del_group.setObjectName("btn_del_group")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_create_group.setText(_translate("Form", "创建群聊"))
        self.btn_add_group.setText(_translate("Form", "添加群聊"))
        self.btn_sendMsg.setText(_translate("Form", "发送"))
        self.toolButton.setText(_translate("Form", "..."))
        self.btn_del_group.setText(_translate("Form", "退群"))
