# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainviewUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1244, 738)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setAutoFillBackground(False)
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setGeometry(QtCore.QRect(115, 9, 1120, 720))
        self.frame_main.setMinimumSize(QtCore.QSize(1120, 720))
        self.frame_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.frame_info = QtWidgets.QFrame(Dialog)
        self.frame_info.setGeometry(QtCore.QRect(9, 9, 100, 720))
        self.frame_info.setMinimumSize(QtCore.QSize(100, 500))
        self.frame_info.setStyleSheet("background-color:rgb(240,240,240)")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_info)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 190, 91, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_chat = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_chat.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_chat.setStyleSheet("QPushButton {background-color: rgb(240,240,240);}\n"
                                    "                                    QPushButton:hover{background-color: rgb(209,209,209);}\n"
                                    "                                ")
        self.btn_chat.setObjectName("btn_chat")
        self.verticalLayout_2.addWidget(self.btn_chat)
        self.btn_contact = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_contact.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_contact.setStyleSheet("QPushButton {background-color: rgb(240,240,240);}\n"
                                       "                                    QPushButton:hover{background-color: rgb(209,209,209);}\n"
                                       "                                ")
        self.btn_contact.setObjectName("btn_contact")
        self.verticalLayout_2.addWidget(self.btn_contact)
        self.btn_myinfo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_myinfo.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_myinfo.setStyleSheet("QPushButton {background-color: rgb(240,240,240);}\n"
                                      "                                    QPushButton:hover{background-color: rgb(209,209,209);}\n"
                                      "                                ")
        self.btn_myinfo.setObjectName("btn_myinfo")
        self.verticalLayout_2.addWidget(self.btn_myinfo)
        self.btn_about = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_about.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_about.setStyleSheet("QPushButton {background-color: rgb(240,240,240);}\n"
                                     "                                    QPushButton:hover{background-color: rgb(209,209,209);}\n"
                                     "                                ")
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout_2.addWidget(self.btn_about)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.myavatar = QtWidgets.QLabel(self.frame_info)
        self.myavatar.setGeometry(QtCore.QRect(10, 40, 80, 80))
        self.myavatar.setObjectName("myavatar")
        self.sign_up = QtWidgets.QPushButton(self.frame_info)
        self.sign_up.setGeometry(QtCore.QRect(0, 0, 40, 28))
        self.sign_up.setObjectName("sign_up")
        self.btn_destroy = QtWidgets.QPushButton(self.frame_info)
        self.btn_destroy.setGeometry(QtCore.QRect(50, 0, 40, 28))
        self.btn_destroy.setObjectName("btn_destroy")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_chat.setText(_translate("Dialog", "聊天"))
        self.btn_contact.setText(_translate("Dialog", "联系人"))
        self.btn_myinfo.setText(_translate("Dialog", "我的"))
        self.btn_about.setText(_translate("Dialog", "关于"))
        self.myavatar.setText(_translate("Dialog", "avatar"))
        self.sign_up.setText(_translate("Dialog", "退出"))
        self.btn_destroy.setText(_translate("Dialog", "注销"))
