# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decryptUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("一纸情书")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(90, 260, 271, 23))
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.label_key = QtWidgets.QLabel(Dialog)
        self.label_key.setGeometry(QtCore.QRect(80, 230, 241, 20))
        self.label_key.setText("")
        self.label_key.setObjectName("label_key")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 80, 245, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_xml = QtWidgets.QPushButton(self.widget)
        self.btn_xml.setObjectName("btn_xml")
        self.horizontalLayout.addWidget(self.btn_xml)
        self.label_xml = QtWidgets.QLabel(self.widget)
        self.label_xml.setObjectName("label_xml")
        self.horizontalLayout.addWidget(self.label_xml)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_db = QtWidgets.QPushButton(self.widget)
        self.btn_db.setObjectName("btn_db")
        self.horizontalLayout_2.addWidget(self.btn_db)
        self.label_db = QtWidgets.QLabel(self.widget)
        self.label_db.setObjectName("label_db")
        self.horizontalLayout_2.addWidget(self.label_db)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "解密数据库"))
        self.btn_xml.setText(_translate("Dialog", "点击加载xml文件"))
        self.label_xml.setText(_translate("Dialog", "xml未就绪"))
        self.btn_db.setText(_translate("Dialog", "点击加载数据库文件"))
        self.label_db.setText(_translate("Dialog", "数据库未就绪"))
        self.pushButton_3.setText(_translate("Dialog", "开始解密数据库"))
