# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinfoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 720)
        Frame.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        Frame.setMouseTracking(True)
        Frame.setTabletTracking(True)
        self.layoutWidget = QtWidgets.QWidget(Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 100, 429, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l_avatar = QtWidgets.QLabel(self.layoutWidget)
        self.l_avatar.setMinimumSize(QtCore.QSize(80, 80))
        self.l_avatar.setMaximumSize(QtCore.QSize(80, 80))
        self.l_avatar.setText("")
        self.l_avatar.setPixmap(QtGui.QPixmap("../../../a_img/be0fa6c0c4707fb5f7b37b660de826d3.jpg"))
        self.l_avatar.setScaledContents(True)
        self.l_avatar.setObjectName("l_avatar")
        self.gridLayout.addWidget(self.l_avatar, 0, 0, 3, 1)
        self.l_remark = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l_remark.setFont(font)
        self.l_remark.setObjectName("l_remark")
        self.gridLayout.addWidget(self.l_remark, 0, 1, 1, 1)
        self.l_nickname = QtWidgets.QLabel(self.layoutWidget)
        self.l_nickname.setObjectName("l_nickname")
        self.gridLayout.addWidget(self.l_nickname, 1, 1, 1, 1)
        self.l_username = QtWidgets.QLabel(self.layoutWidget)
        self.l_username.setObjectName("l_username")
        self.gridLayout.addWidget(self.l_username, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 210, 429, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_outbut = QtWidgets.QPushButton(Frame)
        self.btn_outbut.setGeometry(QtCore.QRect(310, 360, 111, 23))
        self.btn_outbut.setObjectName("btn_outbut")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.l_remark.setText(_translate("Frame", "曹雨萱"))
        self.l_nickname.setText(_translate("Frame", "昵称：997"))
        self.l_username.setText(_translate("Frame", "账号：TextLabel"))
        self.label.setText(_translate("Frame", "备注名"))
        self.lineEdit.setText(_translate("Frame", "曹雨萱"))
        self.btn_outbut.setText(_translate("Frame", "导出聊天记录"))
