# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 394)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_select_all = QtWidgets.QPushButton(Dialog)
        self.btn_select_all.setObjectName("btn_select_all")
        self.horizontalLayout.addWidget(self.btn_select_all)
        self.comboBox_time = QtWidgets.QComboBox(Dialog)
        self.comboBox_time.setObjectName("comboBox_time")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_time)
        self.comboBox_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_type)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_time = QtWidgets.QLabel(Dialog)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_3.addWidget(self.label_time)
        self.label_process = QtWidgets.QLabel(Dialog)
        self.label_process.setText("")
        self.label_process.setObjectName("label_process")
        self.horizontalLayout_3.addWidget(self.label_process)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_start = QtWidgets.QPushButton(Dialog)
        self.btn_start.setStyleSheet("QPushButton{\n"
"    background-color: rgb(233,233,233);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover { \n"
"    background-color: lightgray;\n"
"border:1px solid rgb(31,156,220) ;\n"
"}")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_3.addWidget(self.btn_start)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(233,233,233);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover { \n"
"    background-color: lightgray;\n"
"border:1px solid rgb(31,156,220) ;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "导出过程中请不要退出"))
        self.btn_select_all.setText(_translate("Dialog", "全选"))
        self.comboBox_time.setItemText(0, _translate("Dialog", "全部时间"))
        self.comboBox_time.setItemText(1, _translate("Dialog", "最近三个月"))
        self.comboBox_time.setItemText(2, _translate("Dialog", "自定义时间"))
        self.comboBox_type.setItemText(0, _translate("Dialog", "全部聊天记录"))
        self.comboBox_type.setItemText(1, _translate("Dialog", "不含图片/视频/文件"))
        self.label_2.setText(_translate("Dialog", "消息类型"))
        self.btn_start.setText(_translate("Dialog", "开始"))
        self.btn_cancel.setText(_translate("Dialog", "取消"))
